jtype: UIEExecutor
py_modules:
  - executor.py
metas:
  name: UIEExecutor
  description: Paddle UIE Executor
  url: https://github.com/jina-ai/jina-paddle-hackathon
  keywords: ['nlp', 'information extraction', 'paddlenlp', 'paddlepaddle', 'uie']